#!/usr/bin/env python3
"""
Build the nationwide Wrangler search report (PDF): reliable years only, teen
driver, $7,000-$12,000. The candidate table is generated by wrangler_filter.py,
so the report always matches the filter's current rules.

Usage:  python3 build_wrangler_nationwide_report.py [output.pdf]
"""
import sys
from datetime import date

from reportlab.platypus import CondPageBreak, NextPageTemplate, PageBreak

from build_report import (AMBER, GREEN, GREY, OLIVE, RULE, RUST, S, SAND, KeepTogether, P,
                          Paragraph, Spacer, Table, TableStyle, build, bullets, callout,
                          colors, datatable, hx, inch, rule, tag)
import wrangler_filter as wf

TITLE = 'Nationwide Wrangler Search'
GREEN_BG = colors.HexColor('#eaf1ea')
AMBER_BG = colors.HexColor('#f7f1de')
DECISION_COL = {wf.SHORTLIST: GREEN, wf.CONDITIONAL_D: OLIVE, wf.REVIEW: AMBER,
                wf.EXCLUDED: RUST}

RESULTS = wf.run(wf.CANDIDATES)
COUNT = {k: sum(1 for r in RESULTS if r['decision'] == k)
         for k in (wf.SHORTLIST, wf.CONDITIONAL_D, wf.REVIEW, wf.EXCLUDED)}


def money(v):
    return '$' + format(v, ',') if v else 'n/a'


def story(fw):
    s = [NextPageTemplate('body')]
    s += cover(fw)
    s.append(PageBreak())
    for fn in (section_answer, section_caveats, section_rules, section_budget,
               section_results, section_shortlist, section_leads, section_inspection,
               section_tool, section_plan, section_sources):
        s += fn(fw)
    return s


def cover(fw):
    s = [Spacer(1, 0.92 * inch), P('VEHICLE ACQUISITION RESEARCH', 'cover_lbl'),
         Spacer(1, 5), P('Jeep Wrangler, Nationwide', 'title'),
         P('Reliable years only - filtered automatically from the VIN', 'subtitle'),
         Spacer(1, 0.40 * inch)]
    facts = [
        ['DRIVER', 'High-school student, daily school runs and Colorado ski trips'],
        ['BUDGET', '$7,000 - $12,000 (carried over from the teen-car brief)'],
        ['SEARCH', 'Nationwide, United States. Dry states preferred.'],
        ['APPROVED YEARS', 'JK (preferred): 2015-2017, plus 2014 as second tier.\n'
                           'TJ with the 4.0 inline six: 2003-2004.'],
        ['FILTER RESULT', '%d shortlisted - %d conditional - %d for review - %d excluded\n'
                          '(%d vehicles, every VIN authenticated offline)'
         % (COUNT[wf.SHORTLIST], COUNT[wf.CONDITIONAL_D], COUNT[wf.REVIEW],
            COUNT[wf.EXCLUDED], len(RESULTS))],
        ['REPORT DATE', date.today().strftime('%B %d, %Y')],
    ]
    t = Table([[Paragraph(k, S['cover_lbl']), Paragraph(v.replace('\n', '<br/>'),
                                                        S['cover_val'])] for k, v in facts],
              colWidths=[1.32 * inch, fw - 1.32 * inch])
    t.setStyle(TableStyle([('VALIGN', (0, 0), (-1, -1), 'TOP'),
                           ('LEFTPADDING', (0, 0), (-1, -1), 0),
                           ('TOPPADDING', (0, 0), (-1, -1), 5),
                           ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
                           ('LINEBELOW', (0, 0), (-1, -2), 0.4, RULE)]))
    s += [t, Spacer(1, 0.2 * inch)]
    s.append(callout(
        'The short answer',
        'Reliable-year Wranglers <b>are</b> reachable for $12,000 nationwide - but only as '
        '<b>two-door 2014-2016 JK Sports with roughly 100,000-150,000 miles</b>, or a '
        '<b>2003-2004 TJ</b>. Four-door Unlimiteds in the good years start above your '
        'ceiling. The strongest leads are dry-state 2015-2016 two-doors in California and '
        'Arizona. Read Section 2 before buying: the TJ has no stability control, and any '
        'good-year JK priced far below book is almost certainly hiding a branded title.',
        accent=GREEN, bg=GREEN_BG))
    s += [Spacer(1, 0.08 * inch), P('<b>CONTENTS</b>', 'cover_lbl'), Spacer(1, 3)]
    for c in ['1.  What the search found', '2.  The caveats', '3.  The filter rules',
              '4.  What $12,000 buys in the approved years', '5.  Filter results - all %d '
              'vehicles' % len(RESULTS), '6.  Shortlist and next actions',
              '7.  Leads still missing a VIN', '8.  Generation-specific inspection points',
              '9.  Running the filter yourself', '10. Action plan', '11. Sources']:
        s.append(Paragraph(c, S['toc']))
    return s


def section_answer(fw):
    s = [P('1.  What the search found', 'h1'), rule()]
    s.append(P(
        'Every listing was put through an automatic filter (Section 3) that reads the model '
        'year, generation and engine from the <b>VIN</b> rather than the advert, then applies '
        'your rules: bad years out, JK preferred, inline-six TJs allowed only in their best '
        'years. It also removes total-loss and out-of-country cars, and anything over budget. '
        'Of %d vehicles, %d made the shortlist.' % (len(RESULTS), COUNT[wf.SHORTLIST]), 'body'))
    s.append(callout(
        'The four leads worth calling first',
        [P('<b>1. 1C4AJWAGXFL566836 - 2015 JK Sport, $11,499.</b> Filter rank 1: a '
           'best-rated year, in budget and priced in line with book. Location and mileage '
           'were not indexed - ask both first.', 'callb'), Spacer(1, 4),
         P('<b>2. 1C4AJWAG7FL574988 - 2015 JK Sport automatic, Mesa AZ.</b> Rank 2. '
           'Advertised as a 2014; the VIN proves 2015, which moves it up a tier. Dry climate '
           'and an automatic - easier for a new driver. Get price and mileage.', 'callb'),
         Spacer(1, 4),
         P('<b>3. 1C4AJWAG9GL189210 - 2016 JK Sport, 91,322 mi, Upland CA.</b> Rank 3, and '
           'the car I would most like to own: best-rated year, the lowest mileage of any '
           'two-door found, dry Southern California. It ranks third only because no price '
           'was indexed - a 2016 Sport books at $13,270-$15,620, so it may land over budget.',
           'callb'), Spacer(1, 4),
         P('<b>4. 1J4FA49S34P771921 - 2004 TJ Sport 4.0, 5-speed, $10,859, 135,658 mi, '
           'Garner NC.</b> Rank 7, but the best inline-six: the only one with complete data, a '
           'best TJ year and a fair price. A manual with no stability control (Section 2), and '
           'North Carolina treats winter roads, so inspect the frame.', 'callb'),
         Spacer(1, 4),
         P('Rank 4, a 2016 Sport S at $11,999 in Chantilly VA, is left off this list on '
           'purpose: it is a Virginia road-salt car with 141,399 miles. It stays on the '
           'shortlist in Section 6 if the dry-state options fall through.', 'callb')],
        accent=GREEN, bg=GREEN_BG))
    return s


def section_caveats(fw):
    s = [CondPageBreak(3.0 * inch), P('2.  The caveats', 'h1'), rule()]
    s.append(P('You asked for more of these. In order of how much they should affect the '
               'decision:', 'body'))
    rows = [
        ['The TJ has no stability control', 'Electronic stability control became standard '
         'on the Wrangler with the 2007 JK. No TJ has it. It is one of the IIHS baseline '
         'requirements for a teen car and the single strongest reason to prefer the JK for '
         'this driver. Neither generation has side-curtain airbags.', RUST],
        ['Budget forces high miles and two doors', 'The approved years book at $10,930-'
         '$15,810 for two-doors and from $12,200 for Unlimiteds. At $12,000 expect a two-door '
         'Sport with 100k-150k miles. About $13,000-$14,000 buys noticeably lower miles; '
         'that is the stretch worth considering if any is.', AMBER],
        ['Cheap good-year JKs are usually branded', 'A 2015-2016 well under book is the price '
         'signature of a salvage or rebuilt title, or a major fault. The filter flags anything '
         'more than 15% under book. Treat it as branded until an NMVTIS check says otherwise.',
         RUST],
        ['Part-time 4WD on both generations', 'Both are rear-wheel drive until the driver '
         'engages 4WD, and 4WD must not be left on over dry pavement. Teach when to use 4H, '
         'and fit winter tyres - Colorado\'s November 2025 traction-law update requires rated '
         'tyres even on 4WD vehicles.', AMBER],
        ['Many of these are manuals', 'Most TJs found are 5-speed manuals, and several 2014 '
         'JKs are 6-speed manuals. A stick is one more thing for a new driver to manage. The '
         'VIN does not encode the transmission - confirm it from the listing.', AMBER],
        ['A 2003-2004 TJ is 22-23 years old', 'The 4.0 is famously durable, but rubber, '
         'bushings, wiring and seals have aged regardless of mileage. Parts are cheap; '
         'labour still adds up.', GREY],
        ['Still not on the IIHS teen list', 'Nothing about this filter changes the earlier '
         'safety finding. Within the Wrangler line, a 2015-2017 JK is the best answer; it is '
         'not a teen-list vehicle.', GREY],
        ['The listing data is unreliable', 'Two adverts in this search had the wrong model '
         'year - the filter caught both from the VIN. Price, mileage and location are '
         'REPORTED. The engine rule reads a VIN pattern that held on every Wrangler examined; '
         'confirm at vpic.nhtsa.dot.gov.', GREY],
    ]
    s.append(datatable(['Caveat', 'Why it matters', ''],
                       [[Paragraph('<b>%s</b>' % a, S['cell']), Paragraph(b, S['cell']),
                         Paragraph('<font color="%s"><b>%s</b></font>' % (
                             hx(c), {RUST: 'HIGH', AMBER: 'MED', GREY: 'NOTE'}[c]), S['cell'])]
                        for a, b, c in rows],
                       [1.6 * inch, fw - 2.15 * inch, 0.55 * inch]))
    return s


def section_rules(fw):
    s = [CondPageBreak(3.0 * inch), P('3.  The filter rules', 'h1'), rule()]
    s.append(P('3.1  Model years', 'h2'))
    yrows = []
    for y in range(1997, 2019):
        if y in wf.APPROVED:
            g, tier, why = wf.APPROVED[y]
            yrows.append([str(y), g, tag('TIER ' + tier, GREEN if tier == 'A' else OLIVE), why])
        elif y in wf.CONDITIONAL:
            g, why = wf.CONDITIONAL[y]
            yrows.append([str(y), g, tag('CONDITIONAL', OLIVE), why])
        else:
            yrows.append([str(y), 'TJ' if y < 2007 else 'JK', tag('EXCLUDED', RUST),
                          wf.EXCLUDED_YEARS[y]])
    # Collapse consecutive years that share a verdict and reason.
    merged = []
    for r in yrows:
        key = (r[1], r[2].text, r[3])
        if merged and merged[-1][0] == key:
            merged[-1][1].append(r[0])
        else:
            merged.append([key, [r[0]], r])
    data = []
    for key, years, r in merged:
        span = years[0] if len(years) == 1 else '%s-%s' % (years[0], years[-1])
        data.append([Paragraph('<b>%s</b>' % span, S['cell']), Paragraph(r[1], S['cell']),
                     r[2], Paragraph(r[3], S['cell'])])
    data.append([Paragraph('<b>2019+</b>', S['cell']), Paragraph('JL', S['cell']),
                 tag('EXCLUDED', RUST), Paragraph('JL generation - outside this search and '
                                                  'above budget', S['cell'])])
    s.append(datatable(['Years', 'Gen', 'Verdict', 'Reason'], data,
                       [0.8 * inch, 0.45 * inch, 1.05 * inch, fw - 2.3 * inch]))
    s.append(Spacer(1, 6))
    s.append(P('3.2  Other automatic exclusions', 'h2'))
    s.append(bullets([
        '<b>Engine</b> - TJs must carry the 4.0 inline six (VIN position 8 = S); JKs the 3.6 '
        'Pentastar (position 8 = G). This removes four-cylinder TJs and 3.8L JKs even when the '
        'advert says otherwise.',
        '<b>Check digit</b> - a VIN that fails is not a genuine VIN.',
        '<b>Title and channel</b> - salvage, rebuilt or flood titles; insurance-auction '
        'total losses; historical sales that are no longer for sale.',
        '<b>Country</b> - non-US listings (a Quebec car surfaced; importing adds cost and '
        'Quebec is heavy-salt).',
        '<b>Price</b> over $12,000.',
        '<b>TJ frames from heavy-salt states</b> - a TJ frame rots from the inside out and '
        'cannot be economically repaired, so a TJ from the Northeast or Midwest is excluded '
        'outright. This is a policy choice; it is one line in the code if you want them '
        'reviewed instead.',
    ]))
    s.append(KeepTogether([P('3.3  Flags - kept, but a person must resolve them', 'h2'), P(
        'Listing year contradicted by the VIN; price or mileage missing; priced over 15% below '
        'book; over 150,000 miles; flood region (Florida, Louisiana, Mississippi, Gulf-coast '
        'Texas); road-salt states; online auctions; modified vehicles; Unlimited body in a '
        'year whose book value starts above budget. Serious flags (below book, flood region, '
        'auction, modified, likely over budget) move a car from SHORTLIST to REVIEW.',
        'body')]))
    s.append(P(
        'Shortlisted cars are ranked by tier, then data completeness, mileage and climate, '
        'with a bonus for the JK - your stated preference, and the only generation with '
        'stability control.', 'small'))
    return s


def section_budget(fw):
    s = [CondPageBreak(3.0 * inch), P('4.  What $12,000 buys in the approved years', 'h1'),
         rule()]
    vals = [
        ['2014 JK Sport S, 2-dr', '$10,930 - $13,030', 'Fair condition sits at $10,930'],
        ['2014 JK Unlimited Sport', '$12,200 - $14,450', 'Starts above budget'],
        ['2015 JK Sport, 2-dr', '$11,440 - $13,590', 'Real listings: $10,499 at 151,816 mi; '
                                                    '$12,495 at 148,000 mi'],
        ['2015 JK Sport S, 2-dr', '$12,500 - $14,900', ''],
        ['2015 JK Unlimited Sport', '$13,190 - $15,790', 'Above budget'],
        ['2016 JK Sport, 2-dr', '$13,270 - $15,620', 'Real listing: $10,995 at 155,451 mi'],
        ['2017 JK Sport S, 2-dr', '$13,710 - $15,810', 'Nationwide listings start ~$12,176'],
        ['2004 TJ (median)', 'about $9,000', 'Listings $9,198-$10,995 at 94k-205k mi'],
        ['2005 / 2006 TJ (median)', 'about $13,980 / $10,950', 'Conditional years'],
    ]
    s.append(datatable(['Vehicle', 'KBB private-party', 'Observed'],
                       vals, [1.9 * inch, 1.7 * inch, fw - 3.6 * inch]))
    s.append(Spacer(1, 6))
    s.append(P(
        'The pattern is consistent: high-mileage two-doors in 2014-2016 cluster between '
        '$10,500 and $12,500, 2017s begin just above your ceiling, and 2003-2004 TJs sit '
        'comfortably inside it. A 2016 at $9,995 with 108,449 miles - which this search found - '
        'is 25% below the bottom of its book range. That is not a bargain until a title check '
        'proves it is one.', 'body'))
    return s


def section_results(fw):
    s = [CondPageBreak(3.0 * inch),
         P('5.  Filter results - all %d vehicles' % len(RESULTS), 'h1'), rule()]
    s.append(P('Generated directly by wrangler_filter.py. VIN, year, generation and body come '
               'from the VIN; price, mileage and location are REPORTED.', 'small'))
    rows = []
    for r in RESULTS:
        loc = ', '.join(x for x in (r.get('city'), r.get('state')) if x) or 'n/a'
        price = money(r['price']) if r.get('price') else 'price n/a'
        miles = format(r['miles'], ',') + ' mi' if r.get('miles') else 'miles n/a'
        reported = '%s<br/>%s | %s<br/>%s' % (r.get('trim', ''), price, miles, loc)
        why = ['<font color="%s">x</font> %s' % (hx(RUST), h) for h in r['hard']]
        why += ['<font color="%s">!</font> %s' % (hx(AMBER), f) for f in r['flags']]
        rows.append([tag(r['decision'], DECISION_COL[r['decision']]),
                     Paragraph(r['vin'], S['mono']),
                     Paragraph('<b>%s</b> %s<br/>%s' % (r['year'], r['gen'] or '',
                                                       r['body']), S['cell']),
                     Paragraph(reported, S['cell']),
                     Paragraph('<br/>'.join(why) or 'Clean', S['cell'])])
    s.append(datatable(['Decision', 'VIN', 'From VIN', 'Reported listing', 'Reasons and flags'],
                       rows, [1.04 * inch, 1.42 * inch, 0.68 * inch, 1.42 * inch,
                              fw - 4.56 * inch]))
    return s


def section_shortlist(fw):
    s = [CondPageBreak(3.0 * inch), P('6.  Shortlist and next actions', 'h1'), rule()]
    action = {
        '1C4AJWAG9GL189210': 'Price first; it may book above budget. Lowest-mileage lead.',
        '1C4AJWAG7FL574988': 'Price and mileage. Confirm automatic, as listed.',
        '1C4AJWAGXFL566836': 'Location and mileage - the price already fits.',
        '1C4GJWAG1GL219309': 'Virginia salt: frame and brake-line photos before travelling.',
        '1C4AJWAG1EL160345': 'Price and mileage. Listed as a manual.',
        '1C4AJWAG8EL147494': 'Price and mileage.',
        '1J4FA49S34P771921': 'Frame inspection (NC winter roads); confirm the teen can drive '
                             'a manual; no stability control.',
        '1C4AJWAG7EL190529': 'Price. Advertised as a 2015, VIN says 2014 - price it as a 2014.',
        '1J4FA49S46P788486': 'Only with OPDA replacement records; price and mileage unknown.',
    }
    rows = []
    rank = 0
    for r in RESULTS:
        if r['decision'] not in (wf.SHORTLIST, wf.CONDITIONAL_D):
            continue
        rank += 1
        loc = ', '.join(x for x in (r.get('city'), r.get('state')) if x) or 'n/a'
        rows.append([Paragraph('<b>%d</b>' % rank, S['cell']),
                     Paragraph(r['vin'], S['mono']),
                     Paragraph('%s %s %s, %s<br/>%s' % (
                         r['year'], r['gen'], r['body'],
                         'conditional' if r['decision'] == wf.CONDITIONAL_D
                         else 'tier ' + r['tier'], loc), S['cell']),
                     Paragraph(action.get(r['vin'], ''), S['cell'])])
    s.append(datatable(['#', 'VIN', 'Car', 'Next action'], rows,
                       [0.3 * inch, 1.42 * inch, 1.55 * inch, fw - 3.27 * inch]))
    s.append(Spacer(1, 6))
    s.append(callout(
        'Worth a second look from the REVIEW pile',
        '<b>1C4AJWAG4GL250009</b> - 2016 Sport, $9,995, 108,449 mi. If NMVTIS and CARFAX '
        'both come back clean, this becomes the best-value car in the report. Until then, '
        'assume a branded title. <b>1J4FA39S83P324624</b> - 2003 TJ X, 60,830 mi, hardtop, '
        'Jacksonville FL: remarkably low miles for a best-year TJ, but Florida means a flood '
        'check before anything else.', accent=AMBER, bg=AMBER_BG))
    return s


def section_leads(fw):
    s = [CondPageBreak(2.6 * inch), P('7.  Leads still missing a VIN', 'h1'), rule()]
    s.append(P('These surfaced without a full VIN, so the filter cannot rule on them yet. Ask '
               'for the VIN and run it (Section 9).', 'body'))
    leads = [
        ['2015 JK Sport', '$10,499', '151,816', 'not indexed', 'High miles; in budget'],
        ['2016 JK Sport', '$10,995', '155,451', 'not indexed', 'High miles; best-rated year'],
        ['2015 JK Sport', '$11,995', '134,251', 'Clearwater, FL', 'Flood region'],
        ['2015 JK Sport', 'not indexed', 'not indexed', 'Kingman, AZ', 'Dry state'],
        ['2004 TJ Sport 4.0, 5-sp', '$9,999', 'not indexed', 'Boerne, TX',
         'Hill Country, not the Gulf coast'],
        ['2004 TJ', '$9,198', '165,311', 'Nashville, TN', 'Moderate winter treatment'],
        ['2004 TJ Sport 4.0', '$10,000', '205,463', 'not indexed', 'Very high miles'],
        ['2004 TJ Sport', '$10,995', '93,886', 'Lewes, DE',
         'Would be auto-excluded: heavy-salt state'],
    ]
    s.append(datatable(['Vehicle', 'Price', 'Miles', 'Location', 'Note'], leads,
                       [1.55 * inch, 0.85 * inch, 0.8 * inch, 1.2 * inch, fw - 4.4 * inch]))
    return s


def section_inspection(fw):
    s = [CondPageBreak(3.0 * inch), P('8.  Generation-specific inspection points', 'h1'),
         rule()]
    s.append(P('Use alongside the full Wrangler checklist in the Jeep report, Section 11.1.',
               'small'))
    blocks = [
        ['JK 2014-2017', [
            'Death-wobble road test at 45-65 mph over seams, on a route you choose',
            'Track bar, ball joints, tie rods, steering damper for play',
            'Pentastar: cold-start noise, misfire codes; full OBD-II scan',
            '4H engages and disengages cleanly; transfer case and differential leaks',
            'Confirm transmission from the listing (many 2014s are 6-speed manuals)',
        ]],
        ['TJ 2003-2004 inline six', [
            'Frame: tap the rails under the central skid plate and at the rear control-arm '
            'mounts - inside-out rot is the deal-breaker',
            'Cylinder head casting: confirm it is not a "0331" head (possible if the head was '
            'ever swapped)',
            'Oil leaks: timing cover, rear main seal, oil pan, valve cover',
            'Age items: steering components, bushings, wiring, soft-top or hardtop seals',
            'Clutch and gearbox condition on the 5-speed manuals',
        ]],
        ['Every car', [
            'NMVTIS title check plus your own CARFAX or AutoCheck',
            'Open recalls at nhtsa.gov/recalls',
            'Three VIN plates match: dash, door jamb, frame stamping',
            'Independent inspection by a shop you chose, before money moves',
        ]],
    ]
    for head, items in blocks:
        rows = [[Paragraph('<b>%s</b>' % head, S['cellh'])]]
        rows += [[Paragraph('<font face="Courier-Bold" color="#7d8a63">[&nbsp;&nbsp;]</font>'
                            '&nbsp;&nbsp;%s' % it, S['cell'])] for it in items]
        t = Table(rows, colWidths=[fw])
        st = [('BACKGROUND', (0, 0), (0, 0), OLIVE), ('GRID', (0, 0), (-1, -1), 0.4, RULE),
              ('LEFTPADDING', (0, 0), (-1, -1), 7), ('RIGHTPADDING', (0, 0), (-1, -1), 7),
              ('TOPPADDING', (0, 0), (-1, -1), 4), ('BOTTOMPADDING', (0, 0), (-1, -1), 4)]
        st += [('BACKGROUND', (0, i), (-1, i), SAND) for i in range(2, len(rows), 2)]
        t.setStyle(TableStyle(st))
        s.append(KeepTogether([t, Spacer(1, 7)]))
    return s


def section_tool(fw):
    s = [CondPageBreak(2.8 * inch), P('9.  Running the filter yourself', 'h1'), rule()]
    s.append(P(
        'The listing sites this report could not reach will load in your browser. When you '
        'find a Wrangler, paste its VIN and listing details into the filter; it applies '
        'exactly the rules in Section 3.', 'body'))
    code = Table([[Paragraph(
        '$ python3 wrangler_filter.py 1C4AJWAG4GL250009 --price 9995 --miles 108449 '
        '--state AZ --city Phoenix<br/><br/>'
        'REVIEW&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;1C4AJWAG4GL250009&nbsp;&nbsp;2016 JK 2-dr'
        '&nbsp;&nbsp;$9,995 | 108,449 mi | Phoenix, AZ<br/>'
        '&nbsp;&nbsp;! Priced 25% below book - assume a branded title until NMVTIS proves '
        'otherwise', S['monos'])]], colWidths=[fw])
    code.setStyle(TableStyle([('BACKGROUND', (0, 0), (-1, -1), colors.HexColor('#f5f4ee')),
                              ('BOX', (0, 0), (-1, -1), 0.5, RULE),
                              ('LEFTPADDING', (0, 0), (-1, -1), 10),
                              ('TOPPADDING', (0, 0), (-1, -1), 8),
                              ('BOTTOMPADDING', (0, 0), (-1, -1), 8)]))
    s += [code, Spacer(1, 6)]
    s.append(P(
        'Options: --price, --miles, --state (two-letter code), --city, --year (the year the '
        'advert claims, so contradictions are caught) and --channel (dealer, private, auction, '
        'insurance-auction). Running it with no arguments re-scores the full candidate set. '
        'Every rule - approved years, budget, book floors, salt and flood regions, the JK '
        'bonus - is a named constant at the top of the file.', 'body'))
    return s


def section_plan(fw):
    s = [CondPageBreak(3.0 * inch), P('10.  Action plan', 'h1'), rule()]
    steps = [
        ['1', 'Call the top four', 'Upland CA 2016, Mesa AZ 2015, the $11,499 2015, the '
         'Garner NC 2004 TJ. Get price, mileage, location, transmission and title status.'],
        ['2', 'Search, then filter', 'CarGurus, Cars.com, Autotrader nationwide: Wrangler '
         '2014-2017 2-door under $12,500, and 2003-2004 under $12,000. Run every VIN through '
         'wrangler_filter.py before calling.'],
        ['3', 'Decide on the stretch', 'If nothing clean appears at $12,000, $13,000-$14,000 '
         'buys lower miles in the same years. Decide now, not at the dealer.'],
        ['4', 'Title before travel', 'NMVTIS plus your own history report on any car you '
         'would fly out for - mandatory on anything flagged below book or flood region.'],
        ['5', 'Remote inspection', 'Independent shop near the seller, using Section 8. A '
         'refusal ends it.'],
        ['6', 'Fly and drive', 'From Arizona or California, the drive home doubles as a '
         'long road test. Register with a DR 2698 VIN verification and a Colorado emissions '
         'test.'],
        ['7', 'Winter tyres and 4WD lesson', 'Rated tyres before 1 September, and an empty-'
         'lot session on when to engage 4H - and when to take it out.'],
    ]
    s.append(datatable(['#', 'Step', 'Detail'],
                       [[Paragraph('<b>%s</b>' % a, S['cell']),
                         Paragraph('<b>%s</b>' % b, S['cell']), Paragraph(c, S['cell'])]
                        for a, b, c in steps], [0.3 * inch, 1.5 * inch, fw - 1.8 * inch]))
    s.append(Spacer(1, 8))
    s.append(callout(
        'The one-line summary',
        'Buy a <b>2015-2016 JK two-door</b> from a dry state, with a clean title, ideally an '
        'automatic, for $10,500-$12,000 - and accept 100k-150k miles as the price of the right '
        'years at this budget. Choose a <b>2003-2004 TJ</b> only knowing it has no stability '
        'control. The filter will keep the bad years out of the search for you.',
        accent=GREEN, bg=GREEN_BG))
    return s


def section_sources(fw):
    s = [CondPageBreak(3.0 * inch), P('11.  Sources', 'h1'), rule()]
    s.append(P('Recovered through server-side search; listing sites could not be fetched '
               'directly.', 'small'))
    groups = [
        ('Model-year reliability', [
            'slashgear.com - best and worst Wrangler years; best and worst 4.0 engine years',
            'carscounsel.com / fatboysoffroad.com - TJ years to avoid (0331 head, OPDA)',
            'theautoinsiderblog.com - most reliable Wrangler years, 2026',
            'Earlier Jeep reports in this repository - JK year-by-year verdicts']),
        ('Safety', [
            'jk-forum.com / jeepspecs.com / rockcrawler.com - stability control introduced '
            'with the 2007 JK',
            'iihs.org - safe vehicles for teens (earlier teen-car report)']),
        ('Values and listings', [
            'kbb.com - 2014 Sport S 2D, 2015 Sport 2D values; listings',
            'iseecars.com / hagerty.com / conceptcarz.com - 2004-2006 TJ values',
            'cars.com / iseecars.com / truecar.com / carfax.com / cargurus.com - nationwide '
            'listings under $12,000-$15,000',
            'vms.autorevo.com dealer brochures; occasionbeaucage.com (Quebec)',
            'classic.com / Bring a Trailer; motorcarclassics.com; rmsothebys.com; bid.cars '
            '(IAAI) - TJ listings and sales',
            'hagerty.com / jk-forum.com / expeditionportal.com - rebuilt-title JK warnings']),
        ('Standards applied offline', [
            'ISO 3779 / 49 CFR Part 565 - VIN check digit (vin_tools.py)',
            'wrangler_filter.py - this report\'s rules, applied to every candidate']),
    ]
    for t, items in groups:
        s.append(P(t, 'h3'))
        s.append(bullets(items, style='small'))
    s.append(rule())
    s.append(P('Research support for a private purchase, not a history report, title search, '
               'inspection or professional advice. Listing data is REPORTED and time-sensitive.',
               'small'))
    return s


if __name__ == '__main__':
    out = sys.argv[1] if len(sys.argv) > 1 else 'Wrangler_Nationwide_Reliable_Years.pdf'
    print('Built:', build(out, story_fn=story, title=TITLE,
                          header_right='Reliable years only  |  Teen driver  |  $7,000-$12,000',
                          subject='Nationwide Jeep Wrangler search, reliable model years only, '
                                  '$7,000-$12,000'))
